SenzaInfo:
  StackName: opscenter
  Parameters:
    - EtcdDomain:
        Description: "Your etcd appliance domain name"
        Default: ""
    - TrustedNetwork:
        Description: "Trusted network to add to the public ELB security group"
        Default: "127.0.0.0/8"
    - ImageVersion:
        Description: "Opscenter version (for ex. 5.2.0-p0)"
        Default: "5.2.0-p0"
    - ApplicationId:
        Description: "The application id according to yourturn"
        Default: "stups-cassandra-opscenter"
      
SenzaComponents:

  - Configuration:
      Type: Senza::StupsAutoConfiguration

  - OpsCenter:
      Type: Senza::TaupageAutoScalingGroup
      InstanceType: "t2.micro"
      SecurityGroups:
        - Fn::GetAtt:
          - StupsCassandraOpsCenterSg
          - GroupId
      ElasticLoadBalancer: OpsCenterLoadBalancer
      TaupageConfig:
        root: true
        runtime: Docker
        application_id: "{{Arguments.ApplicationId}}"
        source: "os-registry.stups.zalan.do/mop/stups-opscenter:{{Arguments.ImageVersion}}"
        etcd_discovery_domain: "{{Arguments.EtcdDomain}}"
        health_check_path: /opscenter/index.html
        # http://docs.datastax.com/en/opscenter/5.0/opsc/reference/opscPorts_r.html
        ports:
          8888: 8888
          61620: 61620

  - OpsCenterLoadBalancer:
      Type: Senza::WeightedDnsElasticLoadBalancer
      HTTPPort: 8888
      HealthCheckPath: /opscenter/index.html
      SecurityGroups:
        - Fn::GetAtt:
          - StupsCassandraOpsCenterLbSg
          - GroupId

Resources:       
  StupsCassandraOpsCenterSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpsCenter ports
      SecurityGroupIngress:
      - IpProtocol: tcp # OpsCenter (opscenterd) receiving traffic from agent
        FromPort: 61620
        ToPort: 61620
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp # Allow access for human reading and health checks
        FromPort: 8888
        ToPort: 8888
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp # SSH
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0        
  StupsCassandraOpsCenterLbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpsCenter LB ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 172.16.0.0/12
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: "{{Arguments.TrustedNetwork}}"

